#!/bin/sh
# description: AMI Task Server

#############################################################################

THIS_SCRIPT=${BASH_SOURCE[0]:-$0}

while [[ -n $(readlink $THIS_SCRIPT) ]]
do
  THIS_SCRIPT=$(readlink $THIS_SCRIPT)
done

AMI_HOME=$(cd $(dirname $THIS_SCRIPT) && pwd)

#############################################################################

status() {
  if [[ -z $(ps -ef | grep "net\.hep\.ami\.task\.Main") ]]
  then
    printf "AMITaskServer:\t\t[stopped]\n"
  else
    printf "AMITaskServer:\t\t[running]\n"
  fi
}

#############################################################################

case "$1" in
  start)
    $AMI_HOME/startAMITaskServer.sh
    ;;
  stop)
    $AMI_HOME/stopAMITaskServer.sh
    ;;
  restart)
    $AMI_HOME/restartAMITaskServer.sh
    ;;
  lock)
    $AMI_HOME/lockAMITaskServer.sh
    ;;
  unlock)
    $AMI_HOME/unlockAMITaskServer.sh
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|lock|unlock|status}"
    exit 1
esac

#############################################################################

exit $?

#############################################################################
